# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 14:20
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160915_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('sentence', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
