# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 18:17
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160915_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
                ('a_price', models.FloatField(blank=True, null=True)),
                ('b_price', models.FloatField(blank=True, null=True)),
                ('c_price', models.FloatField(blank=True, null=True)),
                ('d_price', models.FloatField(blank=True, null=True)),
                ('e_price', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConcertInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('concert_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ConcertInfo')),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iemi', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='concertbid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
