# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170616_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
