# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160920_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelist',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
