# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160915_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concertbid',
            old_name='rank',
            new_name='a_rank',
        ),
        migrations.AddField(
            model_name='concertbid',
            name='b_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concertbid',
            name='c_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concertbid',
            name='concert_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ConcertInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertbid',
            name='d_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concertbid',
            name='e_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
