# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_queuelist_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelist',
            name='daddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuelist',
            name='saddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
