# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160926_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelist',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Driver'),
        ),
    ]
