# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_iot_touch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='touch',
        ),
        migrations.AddField(
            model_name='iot',
            name='light',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
