# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:24
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160928_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.IntegerField(blank=True, null=True)),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
    ]
