# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:16
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='thumbup',
            new_name='thumbups',
        ),
        migrations.AddField(
            model_name='thumbup',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rate'),
        ),
        migrations.AddField(
            model_name='thumbup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
