# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170616_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='touch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
