# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_iot_touch'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='cell1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iot',
            name='cell2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iot',
            name='cell3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iot',
            name='cell4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iot',
            name='cell5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
