# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_rate_thumbups'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
