# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170720_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='cell1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iot',
            name='cell2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iot',
            name='cell3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iot',
            name='cell4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iot',
            name='cell5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
