# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 07:46
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170721_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('cell1', models.TextField(blank=True, null=True)),
                ('cell2', models.TextField(blank=True, null=True)),
                ('cell3', models.TextField(blank=True, null=True)),
                ('cell4', models.TextField(blank=True, null=True)),
                ('cell5', models.TextField(blank=True, null=True)),
                ('cell6', models.TextField(blank=True, null=True)),
                ('cell7', models.TextField(blank=True, null=True)),
            ],
            bases=(app.models._UtilMixin, models.Model),
        ),
    ]
