# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_kugi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
