
YASHA=	yasha --no-extensions -v appmate.yml 


all:
	${YASHA} models.py.jinja
	${YASHA} admin.py.jinja
	${YASHA} filters.py.jinja
	${YASHA} serializers.py.jinja
	${YASHA} views.py.jinja
	${YASHA} routers.py.jinja
